//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
namespace GestioneRimborsi.Core.xsd
{
    // 
    // Codice sorgente generato automaticamente da xsd, versione=4.6.1055.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sgate.ancitel.it/idrico/xsd/")]
    [System.Xml.Serialization.XmlRootAttribute("richiesteSgate", Namespace = "http://www.sgate.ancitel.it/idrico/xsd/", IsNullable = false)]
    public partial class tipoFileRichiesteSgate
    {

        private tipoMessaggio[] messaggioField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("messaggio")]
        public tipoMessaggio[] messaggio
        {
            get
            {
                return this.messaggioField;
            }
            set
            {
                this.messaggioField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sgate.ancitel.it/idrico/xsd/")]
    public partial class tipoMessaggio
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("richiesta", typeof(tipoRichiestaIdrico))]
        [System.Xml.Serialization.XmlElementAttribute("segnalazioneCessazione", typeof(tipoSegnalazioneCessazione))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sgate.ancitel.it/idrico/xsd/")]
    public partial class tipoRichiestaIdrico
    {

        private string protocolloDomandaField;

        private string protocolloRichiestaField;

        private string tipologiaDomandaField;

        private tipoPersonaFisicaRiconosciuta richiedenteField;

        private tipoIndirizzoPostale residenzaField;

        private tipoFornituraIdrica fornituraField;

        private tipoBonus bonusField;

        /// <remarks/>
        public string protocolloDomanda
        {
            get
            {
                return this.protocolloDomandaField;
            }
            set
            {
                this.protocolloDomandaField = value;
            }
        }

        /// <remarks/>
        public string protocolloRichiesta
        {
            get
            {
                return this.protocolloRichiestaField;
            }
            set
            {
                this.protocolloRichiestaField = value;
            }
        }

        /// <remarks/>
        public string tipologiaDomanda
        {
            get
            {
                return this.tipologiaDomandaField;
            }
            set
            {
                this.tipologiaDomandaField = value;
            }
        }

        /// <remarks/>
        public tipoPersonaFisicaRiconosciuta richiedente
        {
            get
            {
                return this.richiedenteField;
            }
            set
            {
                this.richiedenteField = value;
            }
        }

        /// <remarks/>
        public tipoIndirizzoPostale residenza
        {
            get
            {
                return this.residenzaField;
            }
            set
            {
                this.residenzaField = value;
            }
        }

        /// <remarks/>
        public tipoFornituraIdrica fornitura
        {
            get
            {
                return this.fornituraField;
            }
            set
            {
                this.fornituraField = value;
            }
        }

        /// <remarks/>
        public tipoBonus bonus
        {
            get
            {
                return this.bonusField;
            }
            set
            {
                this.bonusField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sgate.ancitel.it/idrico/xsd/")]
    public partial class tipoPersonaFisicaRiconosciuta : tipoPersonaFisica
    {

        private tipoDocumentoRiconoscimento documentoRiconoscimentoField;

        /// <remarks/>
        public tipoDocumentoRiconoscimento documentoRiconoscimento
        {
            get
            {
                return this.documentoRiconoscimentoField;
            }
            set
            {
                this.documentoRiconoscimentoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sgate.ancitel.it/idrico/xsd/")]
    public partial class tipoDocumentoRiconoscimento : tipoProtocolloEnte
    {

        private string enteRilascioField;

        private tipoDocumentoRiconoscimentoTipo tipoField;

        /// <remarks/>
        public string enteRilascio
        {
            get
            {
                return this.enteRilascioField;
            }
            set
            {
                this.enteRilascioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public tipoDocumentoRiconoscimentoTipo tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sgate.ancitel.it/idrico/xsd/")]
    public enum tipoDocumentoRiconoscimentoTipo
    {

        /// <remarks/>
        CARTA_IDENTITA,

        /// <remarks/>
        PASSAPORTO,

        /// <remarks/>
        PATENTE_GUIDA,

        /// <remarks/>
        PATENTE_NAUTICA,

        /// <remarks/>
        LIBRETTO_PENSIONE,

        /// <remarks/>
        PATENTINO_ABILITAZIONE_CONDUZIONE_IMPIANTI_TERMICI,

        /// <remarks/>
        TESSERA_RICONOSCIMENTO,

        /// <remarks/>
        ALTRO,
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tipoDocumentoRiconoscimento))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sgate.ancitel.it/idrico/xsd/")]
    public partial class tipoProtocolloEnte
    {

        private string numeroField;

        private System.DateTime dataField;

        /// <remarks/>
        public string numero
        {
            get
            {
                return this.numeroField;
            }
            set
            {
                this.numeroField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sgate.ancitel.it/idrico/xsd/")]
    public partial class tipoLottoMessaggi
    {

        private string idLottoField;

        private int numeroMessaggiField;

        private tipoMessaggio[] listaMessaggiField;

        /// <remarks/>
        public string idLotto
        {
            get
            {
                return this.idLottoField;
            }
            set
            {
                this.idLottoField = value;
            }
        }

        /// <remarks/>
        public int numeroMessaggi
        {
            get
            {
                return this.numeroMessaggiField;
            }
            set
            {
                this.numeroMessaggiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("messaggio", IsNullable = false)]
        public tipoMessaggio[] listaMessaggi
        {
            get
            {
                return this.listaMessaggiField;
            }
            set
            {
                this.listaMessaggiField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sgate.ancitel.it/idrico/xsd/")]
    public partial class tipoMittente
    {

        private string loginField;

        private string passwordField;

        /// <remarks/>
        public string login
        {
            get
            {
                return this.loginField;
            }
            set
            {
                this.loginField = value;
            }
        }

        /// <remarks/>
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sgate.ancitel.it/idrico/xsd/")]
    public partial class tipoRicevutaSegnalazioneInviata
    {

        private string protocolloSegnalazioneField;

        private string esitoField;

        private object itemField;

        /// <remarks/>
        public string protocolloSegnalazione
        {
            get
            {
                return this.protocolloSegnalazioneField;
            }
            set
            {
                this.protocolloSegnalazioneField = value;
            }
        }

        /// <remarks/>
        public string esito
        {
            get
            {
                return this.esitoField;
            }
            set
            {
                this.esitoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("errore", typeof(tipoErrore))]
        [System.Xml.Serialization.XmlElementAttribute("motivazioneKo", typeof(tipoCodiceDettaglio))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sgate.ancitel.it/idrico/xsd/")]
    public partial class tipoErrore
    {

        private string tipologiaField;

        private int codiceField;

        private string dettaglioField;

        /// <remarks/>
        public string tipologia
        {
            get
            {
                return this.tipologiaField;
            }
            set
            {
                this.tipologiaField = value;
            }
        }

        /// <remarks/>
        public int codice
        {
            get
            {
                return this.codiceField;
            }
            set
            {
                this.codiceField = value;
            }
        }

        /// <remarks/>
        public string dettaglio
        {
            get
            {
                return this.dettaglioField;
            }
            set
            {
                this.dettaglioField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sgate.ancitel.it/idrico/xsd/")]
    public partial class tipoCodiceDettaglio
    {

        private int codiceField;

        private string dettaglioField;

        /// <remarks/>
        public int codice
        {
            get
            {
                return this.codiceField;
            }
            set
            {
                this.codiceField = value;
            }
        }

        /// <remarks/>
        public string dettaglio
        {
            get
            {
                return this.dettaglioField;
            }
            set
            {
                this.dettaglioField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sgate.ancitel.it/idrico/xsd/")]
    public partial class tipoRettificaEsito
    {

        private tipoEsitoAgevolazione nuovoEsitoField;

        /// <remarks/>
        public tipoEsitoAgevolazione nuovoEsito
        {
            get
            {
                return this.nuovoEsitoField;
            }
            set
            {
                this.nuovoEsitoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sgate.ancitel.it/idrico/xsd/")]
    public partial class tipoEsitoAgevolazione
    {

        private string protocolloRichiestaField;

        private string esitoField;

        private object[] itemsField;

        /// <remarks/>
        public string protocolloRichiesta
        {
            get
            {
                return this.protocolloRichiestaField;
            }
            set
            {
                this.protocolloRichiestaField = value;
            }
        }

        /// <remarks/>
        public string esito
        {
            get
            {
                return this.esitoField;
            }
            set
            {
                this.esitoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("difformita", typeof(tipoDifformita))]
        [System.Xml.Serialization.XmlElementAttribute("errore", typeof(tipoErrore))]
        [System.Xml.Serialization.XmlElementAttribute("motivazioneKo", typeof(tipoCodiceDettaglio))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sgate.ancitel.it/idrico/xsd/")]
    public partial class tipoDifformita
    {

        private tipoDifformitaAnagrafica anagraficaDifformeField;

        private string codiceUtenteDifformeField;

        /// <remarks/>
        public tipoDifformitaAnagrafica anagraficaDifforme
        {
            get
            {
                return this.anagraficaDifformeField;
            }
            set
            {
                this.anagraficaDifformeField = value;
            }
        }

        /// <remarks/>
        public string codiceUtenteDifforme
        {
            get
            {
                return this.codiceUtenteDifformeField;
            }
            set
            {
                this.codiceUtenteDifformeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sgate.ancitel.it/idrico/xsd/")]
    public partial class tipoDifformitaAnagrafica
    {

        private int componentiFamigliaAnagraficaField;

        private System.DateTime dataAggiornamentoField;

        /// <remarks/>
        public int componentiFamigliaAnagrafica
        {
            get
            {
                return this.componentiFamigliaAnagraficaField;
            }
            set
            {
                this.componentiFamigliaAnagraficaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime dataAggiornamento
        {
            get
            {
                return this.dataAggiornamentoField;
            }
            set
            {
                this.dataAggiornamentoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sgate.ancitel.it/idrico/xsd/")]
    public partial class tipoSegnalazioneInviata
    {

        private string protocolloSegnalazioneField;

        private tipoRettificaEsito rettificaEsitoField;

        /// <remarks/>
        public string protocolloSegnalazione
        {
            get
            {
                return this.protocolloSegnalazioneField;
            }
            set
            {
                this.protocolloSegnalazioneField = value;
            }
        }

        /// <remarks/>
        public tipoRettificaEsito rettificaEsito
        {
            get
            {
                return this.rettificaEsitoField;
            }
            set
            {
                this.rettificaEsitoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sgate.ancitel.it/idrico/xsd/")]
    public partial class tipoRicezioneMessaggio
    {

        private string itemField;

        private ItemChoiceType itemElementNameField;

        private string esitoField;

        private object item1Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("protocolloRichiesta", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("protocolloSegnalazioneCessazione", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }

        /// <remarks/>
        public string esito
        {
            get
            {
                return this.esitoField;
            }
            set
            {
                this.esitoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("errore", typeof(tipoErrore))]
        [System.Xml.Serialization.XmlElementAttribute("motivazioneKo", typeof(tipoCodiceDettaglio))]
        public object Item1
        {
            get
            {
                return this.item1Field;
            }
            set
            {
                this.item1Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sgate.ancitel.it/idrico/xsd/", IncludeInSchema = false)]
    public enum ItemChoiceType
    {

        /// <remarks/>
        protocolloRichiesta,

        /// <remarks/>
        protocolloSegnalazioneCessazione,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sgate.ancitel.it/idrico/xsd/")]
    public partial class tipoEsitoSegnalazioneCessazione
    {

        private string protocolloSegnalazioneCessazioneField;

        private string esitoField;

        private object[] itemsField;

        /// <remarks/>
        public string protocolloSegnalazioneCessazione
        {
            get
            {
                return this.protocolloSegnalazioneCessazioneField;
            }
            set
            {
                this.protocolloSegnalazioneCessazioneField = value;
            }
        }

        /// <remarks/>
        public string esito
        {
            get
            {
                return this.esitoField;
            }
            set
            {
                this.esitoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("errore", typeof(tipoErrore))]
        [System.Xml.Serialization.XmlElementAttribute("motivazioneKoCessazione", typeof(tipoCodiceDettaglio))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sgate.ancitel.it/idrico/xsd/")]
    public partial class tipoEsitoMessaggio
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("esitoAgevolazione", typeof(tipoEsitoAgevolazione))]
        [System.Xml.Serialization.XmlElementAttribute("esitoSegnalazioneCessazione", typeof(tipoEsitoSegnalazioneCessazione))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sgate.ancitel.it/idrico/xsd/")]
    public partial class tipoSegnalazioneCessazione
    {

        private string protocolloSegnalazioneField;

        private string protocolloRichiestaDiRiferimentoField;

        private System.DateTime dataInizioDecorrenzaCessazioneField;

        private bool dataInizioDecorrenzaCessazioneFieldSpecified;

        private string codiceFiscaleRichiedenteField;

        private string codiceFiscaleIntestatarioField;

        private tipoCodiceDettaglio[] motivazioneCessazioneField;

        /// <remarks/>
        public string protocolloSegnalazione
        {
            get
            {
                return this.protocolloSegnalazioneField;
            }
            set
            {
                this.protocolloSegnalazioneField = value;
            }
        }

        /// <remarks/>
        public string protocolloRichiestaDiRiferimento
        {
            get
            {
                return this.protocolloRichiestaDiRiferimentoField;
            }
            set
            {
                this.protocolloRichiestaDiRiferimentoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime dataInizioDecorrenzaCessazione
        {
            get
            {
                return this.dataInizioDecorrenzaCessazioneField;
            }
            set
            {
                this.dataInizioDecorrenzaCessazioneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataInizioDecorrenzaCessazioneSpecified
        {
            get
            {
                return this.dataInizioDecorrenzaCessazioneFieldSpecified;
            }
            set
            {
                this.dataInizioDecorrenzaCessazioneFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string codiceFiscaleRichiedente
        {
            get
            {
                return this.codiceFiscaleRichiedenteField;
            }
            set
            {
                this.codiceFiscaleRichiedenteField = value;
            }
        }

        /// <remarks/>
        public string codiceFiscaleIntestatario
        {
            get
            {
                return this.codiceFiscaleIntestatarioField;
            }
            set
            {
                this.codiceFiscaleIntestatarioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("motivazioneCessazione")]
        public tipoCodiceDettaglio[] motivazioneCessazione
        {
            get
            {
                return this.motivazioneCessazioneField;
            }
            set
            {
                this.motivazioneCessazioneField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sgate.ancitel.it/idrico/xsd/")]
    public partial class tipoBonus
    {

        private int componentiFamigliaAnagraficaField;

        private System.DateTime dataDisponibilitaField;

        private System.DateTime dataAmmissioneField;

        private System.DateTime dataPresentazioneField;

        private System.DateTime dataInizioAgevolazioneField;

        private System.DateTime dataFineAgevolazioneField;

        private bool allineamentoField;

        private bool allineamentoFieldSpecified;

        private bool fruizioneContinuativaField;

        private bool fruizioneContinuativaFieldSpecified;

        /// <remarks/>
        public int componentiFamigliaAnagrafica
        {
            get
            {
                return this.componentiFamigliaAnagraficaField;
            }
            set
            {
                this.componentiFamigliaAnagraficaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime dataDisponibilita
        {
            get
            {
                return this.dataDisponibilitaField;
            }
            set
            {
                this.dataDisponibilitaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime dataAmmissione
        {
            get
            {
                return this.dataAmmissioneField;
            }
            set
            {
                this.dataAmmissioneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime dataPresentazione
        {
            get
            {
                return this.dataPresentazioneField;
            }
            set
            {
                this.dataPresentazioneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime dataInizioAgevolazione
        {
            get
            {
                return this.dataInizioAgevolazioneField;
            }
            set
            {
                this.dataInizioAgevolazioneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime dataFineAgevolazione
        {
            get
            {
                return this.dataFineAgevolazioneField;
            }
            set
            {
                this.dataFineAgevolazioneField = value;
            }
        }

        /// <remarks/>
        public bool allineamento
        {
            get
            {
                return this.allineamentoField;
            }
            set
            {
                this.allineamentoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool allineamentoSpecified
        {
            get
            {
                return this.allineamentoFieldSpecified;
            }
            set
            {
                this.allineamentoFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool fruizioneContinuativa
        {
            get
            {
                return this.fruizioneContinuativaField;
            }
            set
            {
                this.fruizioneContinuativaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fruizioneContinuativaSpecified
        {
            get
            {
                return this.fruizioneContinuativaFieldSpecified;
            }
            set
            {
                this.fruizioneContinuativaFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sgate.ancitel.it/idrico/xsd/")]
    public partial class tipoFornituraCentralizzataIdrico
    {

        private string codiceUtenteField;

        private string codiceIbanField;

        private string denominazioneCondominioField;

        private bool edificioPlurifamiliareField;

        private bool edificioPlurifamiliareFieldSpecified;

        private tipoIndirizzoPostale[] indirizziCentralizzataField;

        /// <remarks/>
        public string codiceUtente
        {
            get
            {
                return this.codiceUtenteField;
            }
            set
            {
                this.codiceUtenteField = value;
            }
        }

        /// <remarks/>
        public string codiceIban
        {
            get
            {
                return this.codiceIbanField;
            }
            set
            {
                this.codiceIbanField = value;
            }
        }

        /// <remarks/>
        public string denominazioneCondominio
        {
            get
            {
                return this.denominazioneCondominioField;
            }
            set
            {
                this.denominazioneCondominioField = value;
            }
        }

        /// <remarks/>
        public bool edificioPlurifamiliare
        {
            get
            {
                return this.edificioPlurifamiliareField;
            }
            set
            {
                this.edificioPlurifamiliareField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool edificioPlurifamiliareSpecified
        {
            get
            {
                return this.edificioPlurifamiliareFieldSpecified;
            }
            set
            {
                this.edificioPlurifamiliareFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("indirizzoFornituraCentralizzata", IsNullable = false)]
        public tipoIndirizzoPostale[] indirizziCentralizzata
        {
            get
            {
                return this.indirizziCentralizzataField;
            }
            set
            {
                this.indirizziCentralizzataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sgate.ancitel.it/idrico/xsd/")]
    public partial class tipoIndirizzoPostale
    {

        private string comuneField;

        private string areaDiCircolazioneField;

        private string numeroCivicoField;

        private string edificioField;

        private string scalaField;

        private string internoField;

        private string capField;

        /// <remarks/>
        public string comune
        {
            get
            {
                return this.comuneField;
            }
            set
            {
                this.comuneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string areaDiCircolazione
        {
            get
            {
                return this.areaDiCircolazioneField;
            }
            set
            {
                this.areaDiCircolazioneField = value;
            }
        }

        /// <remarks/>
        public string numeroCivico
        {
            get
            {
                return this.numeroCivicoField;
            }
            set
            {
                this.numeroCivicoField = value;
            }
        }

        /// <remarks/>
        public string edificio
        {
            get
            {
                return this.edificioField;
            }
            set
            {
                this.edificioField = value;
            }
        }

        /// <remarks/>
        public string scala
        {
            get
            {
                return this.scalaField;
            }
            set
            {
                this.scalaField = value;
            }
        }

        /// <remarks/>
        public string interno
        {
            get
            {
                return this.internoField;
            }
            set
            {
                this.internoField = value;
            }
        }

        /// <remarks/>
        public string cap
        {
            get
            {
                return this.capField;
            }
            set
            {
                this.capField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sgate.ancitel.it/idrico/xsd/")]
    public partial class tipoFornituraIndividualeIdrico
    {

        private string codiceUtenteField;

        private tipoPersonaFisicaRiconosciuta intestatarioField;

        private tipoIndirizzoPostale indirizzoField;

        /// <remarks/>
        public string codiceUtente
        {
            get
            {
                return this.codiceUtenteField;
            }
            set
            {
                this.codiceUtenteField = value;
            }
        }

        /// <remarks/>
        public tipoPersonaFisicaRiconosciuta intestatario
        {
            get
            {
                return this.intestatarioField;
            }
            set
            {
                this.intestatarioField = value;
            }
        }

        /// <remarks/>
        public tipoIndirizzoPostale indirizzo
        {
            get
            {
                return this.indirizzoField;
            }
            set
            {
                this.indirizzoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sgate.ancitel.it/idrico/xsd/")]
    public partial class tipoFornituraIdrica
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fornituraCentralizzata", typeof(tipoFornituraCentralizzataIdrico))]
        [System.Xml.Serialization.XmlElementAttribute("fornituraIndividuale", typeof(tipoFornituraIndividualeIdrico))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tipoPersonaFisicaRiconosciuta))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sgate.ancitel.it/idrico/xsd/")]
    public partial class tipoPersonaFisica
    {

        private string nomeField;

        private string cognomeField;

        private string codiceFiscaleField;

        /// <remarks/>
        public string nome
        {
            get
            {
                return this.nomeField;
            }
            set
            {
                this.nomeField = value;
            }
        }

        /// <remarks/>
        public string cognome
        {
            get
            {
                return this.cognomeField;
            }
            set
            {
                this.cognomeField = value;
            }
        }

        /// <remarks/>
        public string codiceFiscale
        {
            get
            {
                return this.codiceFiscaleField;
            }
            set
            {
                this.codiceFiscaleField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sgate.ancitel.it/idrico/xsd/")]
    [System.Xml.Serialization.XmlRootAttribute("esitiGestore", Namespace = "http://www.sgate.ancitel.it/idrico/xsd/", IsNullable = false)]
    public partial class tipoFileEsitiGestore
    {

        private tipoEsitoMessaggio[] esitoMessaggioField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("esitoMessaggio")]
        public tipoEsitoMessaggio[] esitoMessaggio
        {
            get
            {
                return this.esitoMessaggioField;
            }
            set
            {
                this.esitoMessaggioField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sgate.ancitel.it/idrico/xsd/")]
    [System.Xml.Serialization.XmlRootAttribute("ricezioniEsitiSGATE", Namespace = "http://www.sgate.ancitel.it/idrico/xsd/", IsNullable = false)]
    public partial class tipoFileRicezioniEsitiSGATE
    {

        private tipoRicezioneMessaggio[] ricezioneMessaggioField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ricezioneMessaggio")]
        public tipoRicezioneMessaggio[] ricezioneMessaggio
        {
            get
            {
                return this.ricezioneMessaggioField;
            }
            set
            {
                this.ricezioneMessaggioField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sgate.ancitel.it/idrico/xsd/")]
    [System.Xml.Serialization.XmlRootAttribute("segnalazioniGestore", Namespace = "http://www.sgate.ancitel.it/idrico/xsd/", IsNullable = false)]
    public partial class tipoFileSegnalazioniGestore
    {

        private tipoSegnalazioneInviata[] segnalazioneField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("segnalazione")]
        public tipoSegnalazioneInviata[] segnalazione
        {
            get
            {
                return this.segnalazioneField;
            }
            set
            {
                this.segnalazioneField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sgate.ancitel.it/idrico/xsd/")]
    [System.Xml.Serialization.XmlRootAttribute("ricevuteSegnalazioniSGATE", Namespace = "http://www.sgate.ancitel.it/idrico/xsd/", IsNullable = false)]
    public partial class tipoFileRicevuteSegnalazioniSGATE
    {

        private tipoRicevutaSegnalazioneInviata[] ricevutaSegnalazioneField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ricevutaSegnalazione")]
        public tipoRicevutaSegnalazioneInviata[] ricevutaSegnalazione
        {
            get
            {
                return this.ricevutaSegnalazioneField;
            }
            set
            {
                this.ricevutaSegnalazioneField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sgate.ancitel.it/idrico/xsd/")]
    [System.Xml.Serialization.XmlRootAttribute("richiestaPresaInCaricoLotto", Namespace = "http://www.sgate.ancitel.it/idrico/xsd/", IsNullable = false)]
    public partial class tipoRichiestaPresaInCaricoLotto
    {

        private tipoMittente mittenteField;

        private string idUltimoLottoRicevutoCorrettamenteField;

        private int numeroMessaggiField;

        /// <remarks/>
        public tipoMittente mittente
        {
            get
            {
                return this.mittenteField;
            }
            set
            {
                this.mittenteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string idUltimoLottoRicevutoCorrettamente
        {
            get
            {
                return this.idUltimoLottoRicevutoCorrettamenteField;
            }
            set
            {
                this.idUltimoLottoRicevutoCorrettamenteField = value;
            }
        }

        /// <remarks/>
        public int numeroMessaggi
        {
            get
            {
                return this.numeroMessaggiField;
            }
            set
            {
                this.numeroMessaggiField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sgate.ancitel.it/idrico/xsd/")]
    [System.Xml.Serialization.XmlRootAttribute("rispostaPresaInCaricoLotto", Namespace = "http://www.sgate.ancitel.it/idrico/xsd/", IsNullable = false)]
    public partial class tipoRispostaPresaInCaricoLotto
    {

        private tipoLottoMessaggi lottoMessaggiField;

        private System.Nullable<System.DateTime> dataMessaggioPiuVecchioInCodaField;

        private System.Nullable<int> numeroMessaggiInCodaField;

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public tipoLottoMessaggi lottoMessaggi
        {
            get
            {
                return this.lottoMessaggiField;
            }
            set
            {
                this.lottoMessaggiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", IsNullable = true)]
        public System.Nullable<System.DateTime> dataMessaggioPiuVecchioInCoda
        {
            get
            {
                return this.dataMessaggioPiuVecchioInCodaField;
            }
            set
            {
                this.dataMessaggioPiuVecchioInCodaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> numeroMessaggiInCoda
        {
            get
            {
                return this.numeroMessaggiInCodaField;
            }
            set
            {
                this.numeroMessaggiInCodaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("erroreGenerale", typeof(tipoErrore), IsNullable = true)]
        [System.Xml.Serialization.XmlElementAttribute("ricezionePreseInCarico", typeof(tipoRispostaPresaInCaricoLottoRicezionePreseInCarico))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sgate.ancitel.it/idrico/xsd/")]
    public partial class tipoRispostaPresaInCaricoLottoRicezionePreseInCarico
    {

        private tipoRicezioneMessaggio[] ricezionePresaInCaricoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ricezionePresaInCarico")]
        public tipoRicezioneMessaggio[] ricezionePresaInCarico
        {
            get
            {
                return this.ricezionePresaInCaricoField;
            }
            set
            {
                this.ricezionePresaInCaricoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sgate.ancitel.it/idrico/xsd/")]
    [System.Xml.Serialization.XmlRootAttribute("invioEsiti", Namespace = "http://www.sgate.ancitel.it/idrico/xsd/", IsNullable = false)]
    public partial class tipoInvioEsiti
    {

        private tipoMittente mittenteField;

        private tipoInvioEsitiListaEsiti listaEsitiField;

        /// <remarks/>
        public tipoMittente mittente
        {
            get
            {
                return this.mittenteField;
            }
            set
            {
                this.mittenteField = value;
            }
        }

        /// <remarks/>
        public tipoInvioEsitiListaEsiti listaEsiti
        {
            get
            {
                return this.listaEsitiField;
            }
            set
            {
                this.listaEsitiField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sgate.ancitel.it/idrico/xsd/")]
    public partial class tipoInvioEsitiListaEsiti
    {

        private tipoEsitoMessaggio[] esitoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("esito")]
        public tipoEsitoMessaggio[] esito
        {
            get
            {
                return this.esitoField;
            }
            set
            {
                this.esitoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sgate.ancitel.it/idrico/xsd/")]
    [System.Xml.Serialization.XmlRootAttribute("ricezioneEsiti", Namespace = "http://www.sgate.ancitel.it/idrico/xsd/", IsNullable = false)]
    public partial class tipoRicezioneEsiti
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("erroreGenerale", typeof(tipoErrore))]
        [System.Xml.Serialization.XmlElementAttribute("risultatiRicezioni", typeof(tipoRicezioneEsitiRisultatiRicezioni))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sgate.ancitel.it/idrico/xsd/")]
    public partial class tipoRicezioneEsitiRisultatiRicezioni
    {

        private tipoRicezioneMessaggio[] risultatoRicezioneField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("risultatoRicezione")]
        public tipoRicezioneMessaggio[] risultatoRicezione
        {
            get
            {
                return this.risultatoRicezioneField;
            }
            set
            {
                this.risultatoRicezioneField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sgate.ancitel.it/idrico/xsd/")]
    [System.Xml.Serialization.XmlRootAttribute("segnalazioniInviate", Namespace = "http://www.sgate.ancitel.it/idrico/xsd/", IsNullable = false)]
    public partial class tipoSegnalazioniInviate
    {

        private tipoMittente mittenteField;

        private tipoSegnalazioneInviata[] segnalazioniField;

        /// <remarks/>
        public tipoMittente mittente
        {
            get
            {
                return this.mittenteField;
            }
            set
            {
                this.mittenteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("segnalazione", IsNullable = false)]
        public tipoSegnalazioneInviata[] segnalazioni
        {
            get
            {
                return this.segnalazioniField;
            }
            set
            {
                this.segnalazioniField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sgate.ancitel.it/idrico/xsd/")]
    [System.Xml.Serialization.XmlRootAttribute("ricevuteSegnalazioniInviate", Namespace = "http://www.sgate.ancitel.it/idrico/xsd/", IsNullable = false)]
    public partial class tipoRicevuteSegnalazioniInviate
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("erroreGenerale", typeof(tipoErrore))]
        [System.Xml.Serialization.XmlElementAttribute("ricevuteSegnalazioni", typeof(tipoRicevuteSegnalazioniInviateRicevuteSegnalazioni))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sgate.ancitel.it/idrico/xsd/")]
    public partial class tipoRicevuteSegnalazioniInviateRicevuteSegnalazioni
    {

        private tipoRicevutaSegnalazioneInviata[] ricevutaSegnalazioneField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ricevutaSegnalazione")]
        public tipoRicevutaSegnalazioneInviata[] ricevutaSegnalazione
        {
            get
            {
                return this.ricevutaSegnalazioneField;
            }
            set
            {
                this.ricevutaSegnalazioneField = value;
            }
        }
    }
}
