//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.18020.
// 
namespace SepaManager.Base.Entity.Sdd
{
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="CBISDDReqLogMsg.00.01.00", Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    [System.Xml.Serialization.XmlRootAttribute("CBISDDReqLogMsg", Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00", IsNullable=false)]
    public partial class CBISDDReqLogMsg000006 {
        
        private CBIGroupHeader2 grpHdrField;
        
        private PaymentInstructionInformation2[] pmtInfField;
        
        /// <remarks/>
        public CBIGroupHeader2 GrpHdr {
            get {
                return this.grpHdrField;
            }
            set {
                this.grpHdrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PmtInf")]
        public PaymentInstructionInformation2[] PmtInf {
            get {
                return this.pmtInfField;
            }
            set {
                this.pmtInfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class CBIGroupHeader2 {
        
        private string msgIdField;
        
        private System.DateTime creDtTmField;
        
        private string nbOfTxsField;
        
        private decimal ctrlSumField;
        
        private CBIPartyIdentification1 initgPtyField;
        
        /// <remarks/>
        public string MsgId {
            get {
                return this.msgIdField;
            }
            set {
                this.msgIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreDtTm {
            get {
                return this.creDtTmField;
            }
            set {
                this.creDtTmField = value;
            }
        }
        
        /// <remarks/>
        public string NbOfTxs {
            get {
                return this.nbOfTxsField;
            }
            set {
                this.nbOfTxsField = value;
            }
        }
        
        /// <remarks/>
        public decimal CtrlSum {
            get {
                return this.ctrlSumField;
            }
            set {
                this.ctrlSumField = value;
            }
        }
        
        /// <remarks/>
        public CBIPartyIdentification1 InitgPty {
            get {
                return this.initgPtyField;
            }
            set {
                this.initgPtyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class CBIPartyIdentification1 {
        
        private string nmField;
        
        private CBIIdType1 idField;
        
        /// <remarks/>
        public string Nm {
            get {
                return this.nmField;
            }
            set {
                this.nmField = value;
            }
        }
        
        /// <remarks/>
        public CBIIdType1 Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class CBIIdType1 {
        
        private CBIGenericIdentification1[] orgIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Othr", IsNullable=false)]
        public CBIGenericIdentification1[] OrgId {
            get {
                return this.orgIdField;
            }
            set {
                this.orgIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class CBIGenericIdentification1 {
        
        private string idField;
        
        private string issrField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Issr {
            get {
                return this.issrField;
            }
            set {
                this.issrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class ContactDetails2 {
        
        private NamePrefix1Code nmPrfxField;
        
        private bool nmPrfxFieldSpecified;
        
        private string nmField;
        
        private string phneNbField;
        
        private string mobNbField;
        
        private string faxNbField;
        
        private string emailAdrField;
        
        private string othrField;
        
        /// <remarks/>
        public NamePrefix1Code NmPrfx {
            get {
                return this.nmPrfxField;
            }
            set {
                this.nmPrfxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NmPrfxSpecified {
            get {
                return this.nmPrfxFieldSpecified;
            }
            set {
                this.nmPrfxFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Nm {
            get {
                return this.nmField;
            }
            set {
                this.nmField = value;
            }
        }
        
        /// <remarks/>
        public string PhneNb {
            get {
                return this.phneNbField;
            }
            set {
                this.phneNbField = value;
            }
        }
        
        /// <remarks/>
        public string MobNb {
            get {
                return this.mobNbField;
            }
            set {
                this.mobNbField = value;
            }
        }
        
        /// <remarks/>
        public string FaxNb {
            get {
                return this.faxNbField;
            }
            set {
                this.faxNbField = value;
            }
        }
        
        /// <remarks/>
        public string EmailAdr {
            get {
                return this.emailAdrField;
            }
            set {
                this.emailAdrField = value;
            }
        }
        
        /// <remarks/>
        public string Othr {
            get {
                return this.othrField;
            }
            set {
                this.othrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public enum NamePrefix1Code {
        
        /// <remarks/>
        DOCT,
        
        /// <remarks/>
        MIST,
        
        /// <remarks/>
        MISS,
        
        /// <remarks/>
        MADM,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class GenericPersonIdentification1 {
        
        private string idField;
        
        private PersonIdentificationSchemeName1Choice schmeNmField;
        
        private string issrField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public PersonIdentificationSchemeName1Choice SchmeNm {
            get {
                return this.schmeNmField;
            }
            set {
                this.schmeNmField = value;
            }
        }
        
        /// <remarks/>
        public string Issr {
            get {
                return this.issrField;
            }
            set {
                this.issrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class PersonIdentificationSchemeName1Choice {
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        Cd,
        
        /// <remarks/>
        Prtry,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class DateAndPlaceOfBirth {
        
        private System.DateTime birthDtField;
        
        private string prvcOfBirthField;
        
        private string cityOfBirthField;
        
        private string ctryOfBirthField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime BirthDt {
            get {
                return this.birthDtField;
            }
            set {
                this.birthDtField = value;
            }
        }
        
        /// <remarks/>
        public string PrvcOfBirth {
            get {
                return this.prvcOfBirthField;
            }
            set {
                this.prvcOfBirthField = value;
            }
        }
        
        /// <remarks/>
        public string CityOfBirth {
            get {
                return this.cityOfBirthField;
            }
            set {
                this.cityOfBirthField = value;
            }
        }
        
        /// <remarks/>
        public string CtryOfBirth {
            get {
                return this.ctryOfBirthField;
            }
            set {
                this.ctryOfBirthField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class PersonIdentification5 {
        
        private DateAndPlaceOfBirth dtAndPlcOfBirthField;
        
        private GenericPersonIdentification1[] othrField;
        
        /// <remarks/>
        public DateAndPlaceOfBirth DtAndPlcOfBirth {
            get {
                return this.dtAndPlcOfBirthField;
            }
            set {
                this.dtAndPlcOfBirthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Othr")]
        public GenericPersonIdentification1[] Othr {
            get {
                return this.othrField;
            }
            set {
                this.othrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class OrganisationIdentificationSchemeName1Choice {
        
        private string itemField;
        
        private ItemChoiceType1 itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType1 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00", IncludeInSchema=false)]
    public enum ItemChoiceType1 {
        
        /// <remarks/>
        Cd,
        
        /// <remarks/>
        Prtry,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class GenericOrganisationIdentification1 {
        
        private string idField;
        
        private OrganisationIdentificationSchemeName1Choice schmeNmField;
        
        private string issrField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public OrganisationIdentificationSchemeName1Choice SchmeNm {
            get {
                return this.schmeNmField;
            }
            set {
                this.schmeNmField = value;
            }
        }
        
        /// <remarks/>
        public string Issr {
            get {
                return this.issrField;
            }
            set {
                this.issrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class OrganisationIdentification4 {
        
        private string bICOrBEIField;
        
        private GenericOrganisationIdentification1[] othrField;
        
        /// <remarks/>
        public string BICOrBEI {
            get {
                return this.bICOrBEIField;
            }
            set {
                this.bICOrBEIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Othr")]
        public GenericOrganisationIdentification1[] Othr {
            get {
                return this.othrField;
            }
            set {
                this.othrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class Party6Choice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrgId", typeof(OrganisationIdentification4))]
        [System.Xml.Serialization.XmlElementAttribute("PrvtId", typeof(PersonIdentification5))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class PartyIdentification32 {
        
        private string nmField;
        
        private CBIPostalAddress6 pstlAdrField;
        
        private Party6Choice idField;
        
        private string ctryOfResField;
        
        private ContactDetails2 ctctDtlsField;
        
        /// <remarks/>
        public string Nm {
            get {
                return this.nmField;
            }
            set {
                this.nmField = value;
            }
        }
        
        /// <remarks/>
        public CBIPostalAddress6 PstlAdr {
            get {
                return this.pstlAdrField;
            }
            set {
                this.pstlAdrField = value;
            }
        }
        
        /// <remarks/>
        public Party6Choice Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string CtryOfRes {
            get {
                return this.ctryOfResField;
            }
            set {
                this.ctryOfResField = value;
            }
        }
        
        /// <remarks/>
        public ContactDetails2 CtctDtls {
            get {
                return this.ctctDtlsField;
            }
            set {
                this.ctctDtlsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class CBIPostalAddress6 {
        
        private AddressType2Code adrTpField;
        
        private bool adrTpFieldSpecified;
        
        private string deptField;
        
        private string subDeptField;
        
        private string strtNmField;
        
        private string bldgNbField;
        
        private string pstCdField;
        
        private string twnNmField;
        
        private string ctrySubDvsnField;
        
        private string ctryField;
        
        private string[] adrLineField;
        
        /// <remarks/>
        public AddressType2Code AdrTp {
            get {
                return this.adrTpField;
            }
            set {
                this.adrTpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdrTpSpecified {
            get {
                return this.adrTpFieldSpecified;
            }
            set {
                this.adrTpFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Dept {
            get {
                return this.deptField;
            }
            set {
                this.deptField = value;
            }
        }
        
        /// <remarks/>
        public string SubDept {
            get {
                return this.subDeptField;
            }
            set {
                this.subDeptField = value;
            }
        }
        
        /// <remarks/>
        public string StrtNm {
            get {
                return this.strtNmField;
            }
            set {
                this.strtNmField = value;
            }
        }
        
        /// <remarks/>
        public string BldgNb {
            get {
                return this.bldgNbField;
            }
            set {
                this.bldgNbField = value;
            }
        }
        
        /// <remarks/>
        public string PstCd {
            get {
                return this.pstCdField;
            }
            set {
                this.pstCdField = value;
            }
        }
        
        /// <remarks/>
        public string TwnNm {
            get {
                return this.twnNmField;
            }
            set {
                this.twnNmField = value;
            }
        }
        
        /// <remarks/>
        public string CtrySubDvsn {
            get {
                return this.ctrySubDvsnField;
            }
            set {
                this.ctrySubDvsnField = value;
            }
        }
        
        /// <remarks/>
        public string Ctry {
            get {
                return this.ctryField;
            }
            set {
                this.ctryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdrLine")]
        public string[] AdrLine {
            get {
                return this.adrLineField;
            }
            set {
                this.adrLineField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public enum AddressType2Code {
        
        /// <remarks/>
        ADDR,
        
        /// <remarks/>
        PBOX,
        
        /// <remarks/>
        HOME,
        
        /// <remarks/>
        BIZZ,
        
        /// <remarks/>
        MLTO,
        
        /// <remarks/>
        DLVY,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class CreditorReferenceType1Choice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(DocumentType3Code))]
        [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public enum DocumentType3Code {
        
        /// <remarks/>
        RADM,
        
        /// <remarks/>
        RPIN,
        
        /// <remarks/>
        FXDR,
        
        /// <remarks/>
        DISP,
        
        /// <remarks/>
        PUOR,
        
        /// <remarks/>
        SCOR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class CreditorReferenceType2 {
        
        private CreditorReferenceType1Choice cdOrPrtryField;
        
        private string issrField;
        
        /// <remarks/>
        public CreditorReferenceType1Choice CdOrPrtry {
            get {
                return this.cdOrPrtryField;
            }
            set {
                this.cdOrPrtryField = value;
            }
        }
        
        /// <remarks/>
        public string Issr {
            get {
                return this.issrField;
            }
            set {
                this.issrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class CreditorReferenceInformation2 {
        
        private CreditorReferenceType2 tpField;
        
        private string refField;
        
        /// <remarks/>
        public CreditorReferenceType2 Tp {
            get {
                return this.tpField;
            }
            set {
                this.tpField = value;
            }
        }
        
        /// <remarks/>
        public string Ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class DocumentAdjustment1 {
        
        private ActiveOrHistoricCurrencyAndAmount amtField;
        
        private CreditDebitCode cdtDbtIndField;
        
        private bool cdtDbtIndFieldSpecified;
        
        private string rsnField;
        
        private string addtlInfField;
        
        /// <remarks/>
        public ActiveOrHistoricCurrencyAndAmount Amt {
            get {
                return this.amtField;
            }
            set {
                this.amtField = value;
            }
        }
        
        /// <remarks/>
        public CreditDebitCode CdtDbtInd {
            get {
                return this.cdtDbtIndField;
            }
            set {
                this.cdtDbtIndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CdtDbtIndSpecified {
            get {
                return this.cdtDbtIndFieldSpecified;
            }
            set {
                this.cdtDbtIndFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Rsn {
            get {
                return this.rsnField;
            }
            set {
                this.rsnField = value;
            }
        }
        
        /// <remarks/>
        public string AddtlInf {
            get {
                return this.addtlInfField;
            }
            set {
                this.addtlInfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class ActiveOrHistoricCurrencyAndAmount {
        
        private string ccyField;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Ccy {
            get {
                return this.ccyField;
            }
            set {
                this.ccyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public enum CreditDebitCode {
        
        /// <remarks/>
        CRDT,
        
        /// <remarks/>
        DBIT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class RemittanceAmount1 {
        
        private ActiveOrHistoricCurrencyAndAmount duePyblAmtField;
        
        private ActiveOrHistoricCurrencyAndAmount dscntApldAmtField;
        
        private ActiveOrHistoricCurrencyAndAmount cdtNoteAmtField;
        
        private ActiveOrHistoricCurrencyAndAmount taxAmtField;
        
        private DocumentAdjustment1[] adjstmntAmtAndRsnField;
        
        private ActiveOrHistoricCurrencyAndAmount rmtdAmtField;
        
        /// <remarks/>
        public ActiveOrHistoricCurrencyAndAmount DuePyblAmt {
            get {
                return this.duePyblAmtField;
            }
            set {
                this.duePyblAmtField = value;
            }
        }
        
        /// <remarks/>
        public ActiveOrHistoricCurrencyAndAmount DscntApldAmt {
            get {
                return this.dscntApldAmtField;
            }
            set {
                this.dscntApldAmtField = value;
            }
        }
        
        /// <remarks/>
        public ActiveOrHistoricCurrencyAndAmount CdtNoteAmt {
            get {
                return this.cdtNoteAmtField;
            }
            set {
                this.cdtNoteAmtField = value;
            }
        }
        
        /// <remarks/>
        public ActiveOrHistoricCurrencyAndAmount TaxAmt {
            get {
                return this.taxAmtField;
            }
            set {
                this.taxAmtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdjstmntAmtAndRsn")]
        public DocumentAdjustment1[] AdjstmntAmtAndRsn {
            get {
                return this.adjstmntAmtAndRsnField;
            }
            set {
                this.adjstmntAmtAndRsnField = value;
            }
        }
        
        /// <remarks/>
        public ActiveOrHistoricCurrencyAndAmount RmtdAmt {
            get {
                return this.rmtdAmtField;
            }
            set {
                this.rmtdAmtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class ReferredDocumentType1Choice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(DocumentType5Code))]
        [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public enum DocumentType5Code {
        
        /// <remarks/>
        MSIN,
        
        /// <remarks/>
        CNFA,
        
        /// <remarks/>
        DNFA,
        
        /// <remarks/>
        CINV,
        
        /// <remarks/>
        CREN,
        
        /// <remarks/>
        DEBN,
        
        /// <remarks/>
        HIRI,
        
        /// <remarks/>
        SBIN,
        
        /// <remarks/>
        CMCN,
        
        /// <remarks/>
        SOAC,
        
        /// <remarks/>
        DISP,
        
        /// <remarks/>
        BOLD,
        
        /// <remarks/>
        VCHR,
        
        /// <remarks/>
        AROI,
        
        /// <remarks/>
        TSUT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class ReferredDocumentType2 {
        
        private ReferredDocumentType1Choice cdOrPrtryField;
        
        private string issrField;
        
        /// <remarks/>
        public ReferredDocumentType1Choice CdOrPrtry {
            get {
                return this.cdOrPrtryField;
            }
            set {
                this.cdOrPrtryField = value;
            }
        }
        
        /// <remarks/>
        public string Issr {
            get {
                return this.issrField;
            }
            set {
                this.issrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class ReferredDocumentInformation3 {
        
        private ReferredDocumentType2 tpField;
        
        private string nbField;
        
        private System.DateTime rltdDtField;
        
        private bool rltdDtFieldSpecified;
        
        /// <remarks/>
        public ReferredDocumentType2 Tp {
            get {
                return this.tpField;
            }
            set {
                this.tpField = value;
            }
        }
        
        /// <remarks/>
        public string Nb {
            get {
                return this.nbField;
            }
            set {
                this.nbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime RltdDt {
            get {
                return this.rltdDtField;
            }
            set {
                this.rltdDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RltdDtSpecified {
            get {
                return this.rltdDtFieldSpecified;
            }
            set {
                this.rltdDtFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class StructuredRemittanceInformation7 {
        
        private ReferredDocumentInformation3[] rfrdDocInfField;
        
        private RemittanceAmount1 rfrdDocAmtField;
        
        private CreditorReferenceInformation2 cdtrRefInfField;
        
        private PartyIdentification32 invcrField;
        
        private PartyIdentification32 invceeField;
        
        private string[] addtlRmtInfField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RfrdDocInf")]
        public ReferredDocumentInformation3[] RfrdDocInf {
            get {
                return this.rfrdDocInfField;
            }
            set {
                this.rfrdDocInfField = value;
            }
        }
        
        /// <remarks/>
        public RemittanceAmount1 RfrdDocAmt {
            get {
                return this.rfrdDocAmtField;
            }
            set {
                this.rfrdDocAmtField = value;
            }
        }
        
        /// <remarks/>
        public CreditorReferenceInformation2 CdtrRefInf {
            get {
                return this.cdtrRefInfField;
            }
            set {
                this.cdtrRefInfField = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentification32 Invcr {
            get {
                return this.invcrField;
            }
            set {
                this.invcrField = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentification32 Invcee {
            get {
                return this.invceeField;
            }
            set {
                this.invceeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AddtlRmtInf")]
        public string[] AddtlRmtInf {
            get {
                return this.addtlRmtInfField;
            }
            set {
                this.addtlRmtInfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class RemittanceInformation5 {
        
        private string[] ustrdField;
        
        private StructuredRemittanceInformation7[] strdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Ustrd")]
        public string[] Ustrd {
            get {
                return this.ustrdField;
            }
            set {
                this.ustrdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Strd")]
        public StructuredRemittanceInformation7[] Strd {
            get {
                return this.strdField;
            }
            set {
                this.strdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class CBIStructuredRegulatoryReporting1 {
        
        private CBIStructuredRegulatoryReporting1CD cdField;
        
        private ActiveOrHistoricCurrencyAndAmount amtField;
        
        private string infField;
        
        /// <remarks/>
        public CBIStructuredRegulatoryReporting1CD Cd {
            get {
                return this.cdField;
            }
            set {
                this.cdField = value;
            }
        }
        
        /// <remarks/>
        public ActiveOrHistoricCurrencyAndAmount Amt {
            get {
                return this.amtField;
            }
            set {
                this.amtField = value;
            }
        }
        
        /// <remarks/>
        public string Inf {
            get {
                return this.infField;
            }
            set {
                this.infField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public enum CBIStructuredRegulatoryReporting1CD {
        
        /// <remarks/>
        INF,
        
        /// <remarks/>
        SNR,
        
        /// <remarks/>
        CVA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class CBIRegulatoryReporting1 {
        
        private CBIRegulatoryReportingType2Code dbtCdtRptgIndField;
        
        private CBIStructuredRegulatoryReporting1 dtlsField;
        
        /// <remarks/>
        public CBIRegulatoryReportingType2Code DbtCdtRptgInd {
            get {
                return this.dbtCdtRptgIndField;
            }
            set {
                this.dbtCdtRptgIndField = value;
            }
        }
        
        /// <remarks/>
        public CBIStructuredRegulatoryReporting1 Dtls {
            get {
                return this.dtlsField;
            }
            set {
                this.dtlsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public enum CBIRegulatoryReportingType2Code {
        
        /// <remarks/>
        CRED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class CBIPurpose1Choice {
        
        private string cdField;
        
        /// <remarks/>
        public string Cd {
            get {
                return this.cdField;
            }
            set {
                this.cdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class CBIFinancialInstitutionIdentification5Choice {
        
        private string bICField;
        
        /// <remarks/>
        public string BIC {
            get {
                return this.bICField;
            }
            set {
                this.bICField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class CBIBranchAndFinancialInstitutionIdentification3 {
        
        private CBIFinancialInstitutionIdentification5Choice finInstnIdField;
        
        /// <remarks/>
        public CBIFinancialInstitutionIdentification5Choice FinInstnId {
            get {
                return this.finInstnIdField;
            }
            set {
                this.finInstnIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class GenericFinancialIdentification1 {
        
        private string idField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class FinancialInstitutionIdentification7 {
        
        private string bICField;
        
        private CBIClearingSystemMemberIdentification1 clrSysMmbIdField;
        
        private GenericFinancialIdentification1 othrField;
        
        /// <remarks/>
        public string BIC {
            get {
                return this.bICField;
            }
            set {
                this.bICField = value;
            }
        }
        
        /// <remarks/>
        public CBIClearingSystemMemberIdentification1 ClrSysMmbId {
            get {
                return this.clrSysMmbIdField;
            }
            set {
                this.clrSysMmbIdField = value;
            }
        }
        
        /// <remarks/>
        public GenericFinancialIdentification1 Othr {
            get {
                return this.othrField;
            }
            set {
                this.othrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class CBIClearingSystemMemberIdentification1 {
        
        private string mmbIdField;
        
        /// <remarks/>
        public string MmbId {
            get {
                return this.mmbIdField;
            }
            set {
                this.mmbIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class BranchAndFinancialInstitutionIdentification3 {
        
        private FinancialInstitutionIdentification7 finInstnIdField;
        
        /// <remarks/>
        public FinancialInstitutionIdentification7 FinInstnId {
            get {
                return this.finInstnIdField;
            }
            set {
                this.finInstnIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class CBIPartyIdentification4 {
        
        private string nmField;
        
        private CBIPostalAddress6 pstlAdrField;
        
        private CBIParty1Choice idField;
        
        private string ctryOfResField;
        
        /// <remarks/>
        public string Nm {
            get {
                return this.nmField;
            }
            set {
                this.nmField = value;
            }
        }
        
        /// <remarks/>
        public CBIPostalAddress6 PstlAdr {
            get {
                return this.pstlAdrField;
            }
            set {
                this.pstlAdrField = value;
            }
        }
        
        /// <remarks/>
        public CBIParty1Choice Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string CtryOfRes {
            get {
                return this.ctryOfResField;
            }
            set {
                this.ctryOfResField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class CBIParty1Choice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrgId", typeof(CBIOrganisationIdentification2))]
        [System.Xml.Serialization.XmlElementAttribute("PrvtId", typeof(CBIPersonIdentification1))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class CBIOrganisationIdentification2 {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BICOrBEI", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Othr", typeof(CBIGenericIdentification1))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class CBIPersonIdentification1 {
        
        private CBIGenericIdentification1 othrField;
        
        /// <remarks/>
        public CBIGenericIdentification1 Othr {
            get {
                return this.othrField;
            }
            set {
                this.othrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class CBIFinancialInstitutionIdentification7 {
        
        private string bICField;
        
        private CBIClearingSystemMemberIdentification1 clrSysMmbIdField;
        
        /// <remarks/>
        public string BIC {
            get {
                return this.bICField;
            }
            set {
                this.bICField = value;
            }
        }
        
        /// <remarks/>
        public CBIClearingSystemMemberIdentification1 ClrSysMmbId {
            get {
                return this.clrSysMmbIdField;
            }
            set {
                this.clrSysMmbIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class BranchAndFinancialInstitutionIdentification4 {
        
        private CBIFinancialInstitutionIdentification7 finInstnIdField;
        
        /// <remarks/>
        public CBIFinancialInstitutionIdentification7 FinInstnId {
            get {
                return this.finInstnIdField;
            }
            set {
                this.finInstnIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class CBIPartyIdentification6 {
        
        private string nmField;
        
        private CBIPostalAddress6 pstlAdrField;
        
        private CBIParty4Choice idField;
        
        private string ctryOfResField;
        
        /// <remarks/>
        public string Nm {
            get {
                return this.nmField;
            }
            set {
                this.nmField = value;
            }
        }
        
        /// <remarks/>
        public CBIPostalAddress6 PstlAdr {
            get {
                return this.pstlAdrField;
            }
            set {
                this.pstlAdrField = value;
            }
        }
        
        /// <remarks/>
        public CBIParty4Choice Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string CtryOfRes {
            get {
                return this.ctryOfResField;
            }
            set {
                this.ctryOfResField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class CBIParty4Choice {
        
        private CBIPersonIdentification2 prvtIdField;
        
        /// <remarks/>
        public CBIPersonIdentification2 PrvtId {
            get {
                return this.prvtIdField;
            }
            set {
                this.prvtIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class CBIPersonIdentification2 {
        
        private CBIGenericIdentification2 othrField;
        
        /// <remarks/>
        public CBIGenericIdentification2 Othr {
            get {
                return this.othrField;
            }
            set {
                this.othrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class CBIGenericIdentification2 {
        
        private string idField;
        
        private PersonIdentificationSchemeName1Choice schmeNmField;
        
        private string issrField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public PersonIdentificationSchemeName1Choice SchmeNm {
            get {
                return this.schmeNmField;
            }
            set {
                this.schmeNmField = value;
            }
        }
        
        /// <remarks/>
        public string Issr {
            get {
                return this.issrField;
            }
            set {
                this.issrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class AmendmentInformationDetails1 {
        
        private string orgnlMndtIdField;
        
        private CBIPartyIdentification6 orgnlCdtrSchmeIdField;
        
        private BranchAndFinancialInstitutionIdentification4 orgnlCdtrAgtField;
        
        private CBIPartyIdentification4 orgnlDbtrField;
        
        private CBICashAccount7 orgnlDbtrAcctField;
        
        private BranchAndFinancialInstitutionIdentification3 orgnlDbtrAgtField;
        
        private System.DateTime orgnlFnlColltnDtField;
        
        private bool orgnlFnlColltnDtFieldSpecified;
        
        private Frequency1Code orgnlFrqcyField;
        
        private bool orgnlFrqcyFieldSpecified;
        
        /// <remarks/>
        public string OrgnlMndtId {
            get {
                return this.orgnlMndtIdField;
            }
            set {
                this.orgnlMndtIdField = value;
            }
        }
        
        /// <remarks/>
        public CBIPartyIdentification6 OrgnlCdtrSchmeId {
            get {
                return this.orgnlCdtrSchmeIdField;
            }
            set {
                this.orgnlCdtrSchmeIdField = value;
            }
        }
        
        /// <remarks/>
        public BranchAndFinancialInstitutionIdentification4 OrgnlCdtrAgt {
            get {
                return this.orgnlCdtrAgtField;
            }
            set {
                this.orgnlCdtrAgtField = value;
            }
        }
        
        /// <remarks/>
        public CBIPartyIdentification4 OrgnlDbtr {
            get {
                return this.orgnlDbtrField;
            }
            set {
                this.orgnlDbtrField = value;
            }
        }
        
        /// <remarks/>
        public CBICashAccount7 OrgnlDbtrAcct {
            get {
                return this.orgnlDbtrAcctField;
            }
            set {
                this.orgnlDbtrAcctField = value;
            }
        }
        
        /// <remarks/>
        public BranchAndFinancialInstitutionIdentification3 OrgnlDbtrAgt {
            get {
                return this.orgnlDbtrAgtField;
            }
            set {
                this.orgnlDbtrAgtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime OrgnlFnlColltnDt {
            get {
                return this.orgnlFnlColltnDtField;
            }
            set {
                this.orgnlFnlColltnDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrgnlFnlColltnDtSpecified {
            get {
                return this.orgnlFnlColltnDtFieldSpecified;
            }
            set {
                this.orgnlFnlColltnDtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Frequency1Code OrgnlFrqcy {
            get {
                return this.orgnlFrqcyField;
            }
            set {
                this.orgnlFrqcyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrgnlFrqcySpecified {
            get {
                return this.orgnlFrqcyFieldSpecified;
            }
            set {
                this.orgnlFrqcyFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class CBICashAccount7 {
        
        private AccountIdentification3Choice idField;
        
        /// <remarks/>
        public AccountIdentification3Choice Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class AccountIdentification3Choice {
        
        private string iBANField;
        
        /// <remarks/>
        public string IBAN {
            get {
                return this.iBANField;
            }
            set {
                this.iBANField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public enum Frequency1Code {
        
        /// <remarks/>
        YEAR,
        
        /// <remarks/>
        MNTH,
        
        /// <remarks/>
        QURT,
        
        /// <remarks/>
        MIAN,
        
        /// <remarks/>
        WEEK,
        
        /// <remarks/>
        DAIL,
        
        /// <remarks/>
        ADHO,
        
        /// <remarks/>
        INDA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class MandateRelatedInformation1 {
        
        private string mndtIdField;
        
        private System.DateTime dtOfSgntrField;
        
        private bool amdmntIndField;
        
        private bool amdmntIndFieldSpecified;
        
        private AmendmentInformationDetails1 amdmntInfDtlsField;
        
        private string elctrncSgntrField;
        
        private System.DateTime frstColltnDtField;
        
        private bool frstColltnDtFieldSpecified;
        
        private System.DateTime fnlColltnDtField;
        
        private bool fnlColltnDtFieldSpecified;
        
        private Frequency1Code frqcyField;
        
        private bool frqcyFieldSpecified;
        
        /// <remarks/>
        public string MndtId {
            get {
                return this.mndtIdField;
            }
            set {
                this.mndtIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DtOfSgntr {
            get {
                return this.dtOfSgntrField;
            }
            set {
                this.dtOfSgntrField = value;
            }
        }
        
        /// <remarks/>
        public bool AmdmntInd {
            get {
                return this.amdmntIndField;
            }
            set {
                this.amdmntIndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AmdmntIndSpecified {
            get {
                return this.amdmntIndFieldSpecified;
            }
            set {
                this.amdmntIndFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public AmendmentInformationDetails1 AmdmntInfDtls {
            get {
                return this.amdmntInfDtlsField;
            }
            set {
                this.amdmntInfDtlsField = value;
            }
        }
        
        /// <remarks/>
        public string ElctrncSgntr {
            get {
                return this.elctrncSgntrField;
            }
            set {
                this.elctrncSgntrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime FrstColltnDt {
            get {
                return this.frstColltnDtField;
            }
            set {
                this.frstColltnDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FrstColltnDtSpecified {
            get {
                return this.frstColltnDtFieldSpecified;
            }
            set {
                this.frstColltnDtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime FnlColltnDt {
            get {
                return this.fnlColltnDtField;
            }
            set {
                this.fnlColltnDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FnlColltnDtSpecified {
            get {
                return this.fnlColltnDtFieldSpecified;
            }
            set {
                this.fnlColltnDtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Frequency1Code Frqcy {
            get {
                return this.frqcyField;
            }
            set {
                this.frqcyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FrqcySpecified {
            get {
                return this.frqcyFieldSpecified;
            }
            set {
                this.frqcyFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class DirectDebitTransaction1 {
        
        private MandateRelatedInformation1 mndtRltdInfField;
        
        private string preNtfctnIdField;
        
        private System.DateTime preNtfctnDtField;
        
        private bool preNtfctnDtFieldSpecified;
        
        /// <remarks/>
        public MandateRelatedInformation1 MndtRltdInf {
            get {
                return this.mndtRltdInfField;
            }
            set {
                this.mndtRltdInfField = value;
            }
        }
        
        /// <remarks/>
        public string PreNtfctnId {
            get {
                return this.preNtfctnIdField;
            }
            set {
                this.preNtfctnIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime PreNtfctnDt {
            get {
                return this.preNtfctnDtField;
            }
            set {
                this.preNtfctnDtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PreNtfctnDtSpecified {
            get {
                return this.preNtfctnDtFieldSpecified;
            }
            set {
                this.preNtfctnDtFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class CBIPaymentTypeInformation2 {
        
        private PaymentCategoryPurpose1Code ctgyPurpField;
        
        /// <remarks/>
        public PaymentCategoryPurpose1Code CtgyPurp {
            get {
                return this.ctgyPurpField;
            }
            set {
                this.ctgyPurpField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class PaymentCategoryPurpose1Code {
        
        private string cdField;
        
        /// <remarks/>
        public string Cd {
            get {
                return this.cdField;
            }
            set {
                this.cdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class CBIPaymentIdentification1 {
        
        private string instrIdField;
        
        private string endToEndIdField;
        
        /// <remarks/>
        public string InstrId {
            get {
                return this.instrIdField;
            }
            set {
                this.instrIdField = value;
            }
        }
        
        /// <remarks/>
        public string EndToEndId {
            get {
                return this.endToEndIdField;
            }
            set {
                this.endToEndIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class DirectDebitTransactionInformation1 {
        
        private CBIPaymentIdentification1 pmtIdField;
        
        private CBIPaymentTypeInformation2 pmtTpInfField;
        
        private ActiveOrHistoricCurrencyAndAmount instdAmtField;
        
        private CBIChargeBearerTypeCode chrgBrField;
        
        private bool chrgBrFieldSpecified;
        
        private DirectDebitTransaction1 drctDbtTxField;
        
        private CBIPartyIdentification3 ultmtCdtrField;
        
        private CBIBranchAndFinancialInstitutionIdentification3 dbtrAgtField;
        
        private CBIPartyIdentification4 dbtrField;
        
        private CBICashAccount7 dbtrAcctField;
        
        private CBIPartyIdentification4 ultmtDbtrField;
        
        private string instrForCdtrAgtField;
        
        private CBIPurpose1Choice purpField;
        
        private CBIRegulatoryReporting1[] rgltryRptgField;
        
        private RemittanceInformation5 rmtInfField;
        
        /// <remarks/>
        public CBIPaymentIdentification1 PmtId {
            get {
                return this.pmtIdField;
            }
            set {
                this.pmtIdField = value;
            }
        }
        
        /// <remarks/>
        public CBIPaymentTypeInformation2 PmtTpInf {
            get {
                return this.pmtTpInfField;
            }
            set {
                this.pmtTpInfField = value;
            }
        }
        
        /// <remarks/>
        public ActiveOrHistoricCurrencyAndAmount InstdAmt {
            get {
                return this.instdAmtField;
            }
            set {
                this.instdAmtField = value;
            }
        }
        
        /// <remarks/>
        public CBIChargeBearerTypeCode ChrgBr {
            get {
                return this.chrgBrField;
            }
            set {
                this.chrgBrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ChrgBrSpecified {
            get {
                return this.chrgBrFieldSpecified;
            }
            set {
                this.chrgBrFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public DirectDebitTransaction1 DrctDbtTx {
            get {
                return this.drctDbtTxField;
            }
            set {
                this.drctDbtTxField = value;
            }
        }
        
        /// <remarks/>
        public CBIPartyIdentification3 UltmtCdtr {
            get {
                return this.ultmtCdtrField;
            }
            set {
                this.ultmtCdtrField = value;
            }
        }
        
        /// <remarks/>
        public CBIBranchAndFinancialInstitutionIdentification3 DbtrAgt {
            get {
                return this.dbtrAgtField;
            }
            set {
                this.dbtrAgtField = value;
            }
        }
        
        /// <remarks/>
        public CBIPartyIdentification4 Dbtr {
            get {
                return this.dbtrField;
            }
            set {
                this.dbtrField = value;
            }
        }
        
        /// <remarks/>
        public CBICashAccount7 DbtrAcct {
            get {
                return this.dbtrAcctField;
            }
            set {
                this.dbtrAcctField = value;
            }
        }
        
        /// <remarks/>
        public CBIPartyIdentification4 UltmtDbtr {
            get {
                return this.ultmtDbtrField;
            }
            set {
                this.ultmtDbtrField = value;
            }
        }
        
        /// <remarks/>
        public string InstrForCdtrAgt {
            get {
                return this.instrForCdtrAgtField;
            }
            set {
                this.instrForCdtrAgtField = value;
            }
        }
        
        /// <remarks/>
        public CBIPurpose1Choice Purp {
            get {
                return this.purpField;
            }
            set {
                this.purpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RgltryRptg")]
        public CBIRegulatoryReporting1[] RgltryRptg {
            get {
                return this.rgltryRptgField;
            }
            set {
                this.rgltryRptgField = value;
            }
        }
        
        /// <remarks/>
        public RemittanceInformation5 RmtInf {
            get {
                return this.rmtInfField;
            }
            set {
                this.rmtInfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public enum CBIChargeBearerTypeCode {
        
        /// <remarks/>
        SLEV,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class CBIPartyIdentification3 {
        
        private string nmField;
        
        private CBIPostalAddress6 pstlAdrField;
        
        private CBIParty1Choice idField;
        
        /// <remarks/>
        public string Nm {
            get {
                return this.nmField;
            }
            set {
                this.nmField = value;
            }
        }
        
        /// <remarks/>
        public CBIPostalAddress6 PstlAdr {
            get {
                return this.pstlAdrField;
            }
            set {
                this.pstlAdrField = value;
            }
        }
        
        /// <remarks/>
        public CBIParty1Choice Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class CBIPartyIdentification2 {
        
        private string nmField;
        
        private CBIPostalAddress6 pstlAdrField;
        
        private CBIParty4Choice idField;
        
        private string ctryOfResField;
        
        /// <remarks/>
        public string Nm {
            get {
                return this.nmField;
            }
            set {
                this.nmField = value;
            }
        }
        
        /// <remarks/>
        public CBIPostalAddress6 PstlAdr {
            get {
                return this.pstlAdrField;
            }
            set {
                this.pstlAdrField = value;
            }
        }
        
        /// <remarks/>
        public CBIParty4Choice Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string CtryOfRes {
            get {
                return this.ctryOfResField;
            }
            set {
                this.ctryOfResField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class CBIFinancialInstitutionIdentification1 {
        
        private CBIClearingSystemMemberIdentification1 clrSysMmbIdField;
        
        /// <remarks/>
        public CBIClearingSystemMemberIdentification1 ClrSysMmbId {
            get {
                return this.clrSysMmbIdField;
            }
            set {
                this.clrSysMmbIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class CBIBranchAndFinancialInstitutionIdentification1 {
        
        private CBIFinancialInstitutionIdentification1 finInstnIdField;
        
        /// <remarks/>
        public CBIFinancialInstitutionIdentification1 FinInstnId {
            get {
                return this.finInstnIdField;
            }
            set {
                this.finInstnIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class LocalInstrument1Choice {
        
        private string cdField;
        
        /// <remarks/>
        public string Cd {
            get {
                return this.cdField;
            }
            set {
                this.cdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class CBIServiceLevel3Choice {
        
        private CBIServiceLevel2Code cdField;
        
        /// <remarks/>
        public CBIServiceLevel2Code Cd {
            get {
                return this.cdField;
            }
            set {
                this.cdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public enum CBIServiceLevel2Code {
        
        /// <remarks/>
        SEPA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class CBIPaymentTypeInformation2_1 {
        
        private CBIServiceLevel3Choice svcLvlField;
        
        private LocalInstrument1Choice lclInstrmField;
        
        private SequenceType1Code seqTpField;
        
        private PaymentCategoryPurpose1Code ctgyPurpField;
        
        /// <remarks/>
        public CBIServiceLevel3Choice SvcLvl {
            get {
                return this.svcLvlField;
            }
            set {
                this.svcLvlField = value;
            }
        }
        
        /// <remarks/>
        public LocalInstrument1Choice LclInstrm {
            get {
                return this.lclInstrmField;
            }
            set {
                this.lclInstrmField = value;
            }
        }
        
        /// <remarks/>
        public SequenceType1Code SeqTp {
            get {
                return this.seqTpField;
            }
            set {
                this.seqTpField = value;
            }
        }
        
        /// <remarks/>
        public PaymentCategoryPurpose1Code CtgyPurp {
            get {
                return this.ctgyPurpField;
            }
            set {
                this.ctgyPurpField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public enum SequenceType1Code {
        
        /// <remarks/>
        FRST,
        
        /// <remarks/>
        RCUR,
        
        /// <remarks/>
        FNAL,
        
        /// <remarks/>
        OOFF,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public partial class PaymentInstructionInformation2 {
        
        private string pmtInfIdField;
        
        private PaymentMethod2Code pmtMtdField;
        
        private bool btchBookgField;
        
        private bool btchBookgFieldSpecified;
        
        private CBIPaymentTypeInformation2_1 pmtTpInfField;
        
        private System.DateTime reqdColltnDtField;
        
        private CBIPartyIdentification3 cdtrField;
        
        private CBICashAccount7 cdtrAcctField;
        
        private CBIBranchAndFinancialInstitutionIdentification1 cdtrAgtField;
        
        private CBIPartyIdentification3 ultmtCdtrField;
        
        private CBIChargeBearerTypeCode chrgBrField;
        
        private bool chrgBrFieldSpecified;
        
        private CBICashAccount7 chrgsAcctField;
        
        private CBIPartyIdentification2 cdtrSchmeIdField;
        
        private DirectDebitTransactionInformation1[] drctDbtTxInfField;
        
        /// <remarks/>
        public string PmtInfId {
            get {
                return this.pmtInfIdField;
            }
            set {
                this.pmtInfIdField = value;
            }
        }
        
        /// <remarks/>
        public PaymentMethod2Code PmtMtd {
            get {
                return this.pmtMtdField;
            }
            set {
                this.pmtMtdField = value;
            }
        }
        
        /// <remarks/>
        public bool BtchBookg {
            get {
                return this.btchBookgField;
            }
            set {
                this.btchBookgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BtchBookgSpecified {
            get {
                return this.btchBookgFieldSpecified;
            }
            set {
                this.btchBookgFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public CBIPaymentTypeInformation2_1 PmtTpInf {
            get {
                return this.pmtTpInfField;
            }
            set {
                this.pmtTpInfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime ReqdColltnDt {
            get {
                return this.reqdColltnDtField;
            }
            set {
                this.reqdColltnDtField = value;
            }
        }
        
        /// <remarks/>
        public CBIPartyIdentification3 Cdtr {
            get {
                return this.cdtrField;
            }
            set {
                this.cdtrField = value;
            }
        }
        
        /// <remarks/>
        public CBICashAccount7 CdtrAcct {
            get {
                return this.cdtrAcctField;
            }
            set {
                this.cdtrAcctField = value;
            }
        }
        
        /// <remarks/>
        public CBIBranchAndFinancialInstitutionIdentification1 CdtrAgt {
            get {
                return this.cdtrAgtField;
            }
            set {
                this.cdtrAgtField = value;
            }
        }
        
        /// <remarks/>
        public CBIPartyIdentification3 UltmtCdtr {
            get {
                return this.ultmtCdtrField;
            }
            set {
                this.ultmtCdtrField = value;
            }
        }
        
        /// <remarks/>
        public CBIChargeBearerTypeCode ChrgBr {
            get {
                return this.chrgBrField;
            }
            set {
                this.chrgBrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ChrgBrSpecified {
            get {
                return this.chrgBrFieldSpecified;
            }
            set {
                this.chrgBrFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public CBICashAccount7 ChrgsAcct {
            get {
                return this.chrgsAcctField;
            }
            set {
                this.chrgsAcctField = value;
            }
        }
        
        /// <remarks/>
        public CBIPartyIdentification2 CdtrSchmeId {
            get {
                return this.cdtrSchmeIdField;
            }
            set {
                this.cdtrSchmeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DrctDbtTxInf")]
        public DirectDebitTransactionInformation1[] DrctDbtTxInf {
            get {
                return this.drctDbtTxInfField;
            }
            set {
                this.drctDbtTxInfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CBI:xsd:CBISDDReqLogMsg.00.01.00")]
    public enum PaymentMethod2Code {
        
        /// <remarks/>
        DD,
    }
}
