//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace GestioneRimborsi.Web.BankXMLManager {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BankXMLManager.IBankXMLService")]
    public interface IBankXMLService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankXMLService/CreateXml", ReplyAction="http://tempuri.org/IBankXMLService/CreateXmlResponse")]
        long CreateXml(string FileName, string PkOperazione, string Autore);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankXMLService/CreateXml", ReplyAction="http://tempuri.org/IBankXMLService/CreateXmlResponse")]
        System.Threading.Tasks.Task<long> CreateXmlAsync(string FileName, string PkOperazione, string Autore);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankXMLService/GetXmlDocument", ReplyAction="http://tempuri.org/IBankXMLService/GetXmlDocumentResponse")]
        SepaManager.Base.BankXMLOutput GetXmlDocument(long SepaHederID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankXMLService/GetXmlDocument", ReplyAction="http://tempuri.org/IBankXMLService/GetXmlDocumentResponse")]
        System.Threading.Tasks.Task<SepaManager.Base.BankXMLOutput> GetXmlDocumentAsync(long SepaHederID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankXMLService/RegenerateXmlDocument", ReplyAction="http://tempuri.org/IBankXMLService/RegenerateXmlDocumentResponse")]
        SepaManager.Base.BankXMLOutput RegenerateXmlDocument(long pkOperazione);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankXMLService/RegenerateXmlDocument", ReplyAction="http://tempuri.org/IBankXMLService/RegenerateXmlDocumentResponse")]
        System.Threading.Tasks.Task<SepaManager.Base.BankXMLOutput> RegenerateXmlDocumentAsync(long pkOperazione);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IBankXMLService/CreateCsvDocument", ReplyAction = "http://tempuri.org/IBankXMLService/CreateCsvDocumentResponse")]
        List<String> CreateCsvDocument(long pkOperazione);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IBankXMLService/CreateCsvDocument", ReplyAction = "http://tempuri.org/IBankXMLService/CreateCsvDocumentResponse")]
        System.Threading.Tasks.Task<List<String>> CreateCsvDocumentAsync(long pkOperazione);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBankXMLServiceChannel : GestioneRimborsi.Web.BankXMLManager.IBankXMLService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BankXMLServiceClient : System.ServiceModel.ClientBase<GestioneRimborsi.Web.BankXMLManager.IBankXMLService>, GestioneRimborsi.Web.BankXMLManager.IBankXMLService {
        
        public BankXMLServiceClient() {
        }
        
        public BankXMLServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BankXMLServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankXMLServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankXMLServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public long CreateXml(string FileName, string PkOperazione, string Autore) {
            return base.Channel.CreateXml(FileName, PkOperazione, Autore);
        }
        
        public System.Threading.Tasks.Task<long> CreateXmlAsync(string FileName, string PkOperazione, string Autore) {
            return base.Channel.CreateXmlAsync(FileName, PkOperazione, Autore);
        }
        
        public SepaManager.Base.BankXMLOutput GetXmlDocument(long SepaHederID) {
            return base.Channel.GetXmlDocument(SepaHederID);
        }
        
        public System.Threading.Tasks.Task<SepaManager.Base.BankXMLOutput> GetXmlDocumentAsync(long SepaHederID) {
            return base.Channel.GetXmlDocumentAsync(SepaHederID);
        }
        
        public SepaManager.Base.BankXMLOutput RegenerateXmlDocument(long pkOperazione) {
            return base.Channel.RegenerateXmlDocument(pkOperazione);
        }        
        
        public System.Threading.Tasks.Task<SepaManager.Base.BankXMLOutput> RegenerateXmlDocumentAsync(long pkOperazione) {
            return base.Channel.RegenerateXmlDocumentAsync(pkOperazione);
        }

        public List<String> CreateCsvDocument(long pkOperazione)
        {
            return base.Channel.CreateCsvDocument(pkOperazione);
        }

        public System.Threading.Tasks.Task<List<String>> CreateCsvDocumentAsync(long pkOperazione)
        {
            return base.Channel.CreateCsvDocumentAsync(pkOperazione);
        }
    }
}
